# Generated by Django 5.1.3 on 2024-12-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_avatar_alter_profile_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry_experiance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
