# Generated by Django 5.1.3 on 2024-12-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Instructions or steps to do the activity.')),
                ('grading_criteria', models.TextField(help_text='Describe the grading rubric.')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Countdown time in minutes.')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('uploaded_file', models.FileField(upload_to='submissions/')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='activities.activity')),
            ],
        ),
    ]
