# Generated by Django 5.1.3 on 2024-12-27 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_objective',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='total_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instruction',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='average_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='excellent_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='good_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='poor_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SelfEfficacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('exercise', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.exercise')),
                ('quiz', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.quiz')),
            ],
        ),
    ]
