# Generated by Django 5.1.3 on 2024-12-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=255)),
                ('excellent_description', models.TextField()),
                ('good_description', models.TextField()),
                ('average_description', models.TextField()),
                ('poor_description', models.TextField()),
                ('weight', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='grading_criteria',
        ),
        migrations.AddField(
            model_name='activity',
            name='grading_criteria',
            field=models.ManyToManyField(related_name='activities', to='activities.gradingrubric'),
        ),
    ]
