# Generated by Django 5.1.3 on 2024-12-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_gradingrubric_remove_activity_grading_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='instructions',
            field=models.TextField(default=1, help_text='Detailed instructions for solving the activity.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='grading_criteria',
            field=models.ManyToManyField(blank=True, related_name='activities', to='activities.gradingrubric'),
        ),
    ]
