# Generated by Django 5.1.3 on 2024-12-27 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_exercise_activity_remove_exercise_total_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_objective',
        ),
        migrations.AddField(
            model_name='exercise',
            name='objective',
            field=models.TextField(default=1, verbose_name='Exercise Objective'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(help_text='Instructions or steps to complete the activity.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Countdown time in minutes.', verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Activity Title'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Exercise Title'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='total_weight',
            field=models.FloatField(default=0.0, verbose_name='Total Weight'),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='activities.activity', verbose_name='Related Activity'),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='average_description',
            field=models.TextField(blank=True, null=True, verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='criteria',
            field=models.CharField(max_length=255, verbose_name='Criteria'),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='excellent_description',
            field=models.TextField(blank=True, null=True, verbose_name='Excellent'),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='good_description',
            field=models.TextField(blank=True, null=True, verbose_name='Good'),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='poor_description',
            field=models.TextField(blank=True, null=True, verbose_name='Poor'),
        ),
        migrations.AlterField(
            model_name='gradingrubric',
            name='weight',
            field=models.FloatField(default=1.0, verbose_name='Weight (%)'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='text',
            field=models.TextField(verbose_name='Instruction Text'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Instruction Title'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='weight',
            field=models.FloatField(verbose_name='Weight (%)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1.0, verbose_name='Weight (%)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='activities.activity', verbose_name='Related Activity'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Quiz Title'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='Total Score'),
        ),
        migrations.AlterField(
            model_name='score',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Score'),
        ),
        migrations.AlterField(
            model_name='selfefficacy',
            name='confidence_score',
            field=models.FloatField(default=0.0, verbose_name='Confidence Score'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='activities.exercise'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Reviewed'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submission Time'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='uploaded_file',
            field=models.FileField(upload_to='submissions/', verbose_name='Uploaded File'),
        ),
    ]
