# Generated by Django 5.1.3 on 2024-12-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='grading_criteria',
        ),
        migrations.AddField(
            model_name='gradingrubric',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='activities.activity'),
            preserve_default=False,
        ),
    ]
